instructions:
  add:
    name: add
    format: "R"
    opcode: 0b0110011
    funct3: 0b000
    funct7: 0b0000000
    code: !ruby/code |
      rd[]= rs1 + rs2
  sub:
    name: sub
    format: "R"
    opcode: 0b0110011
    funct3: 0b000
    funct7: 0b0100000
    code: !ruby/code |
      rd[]= rs1 - rs2