#pragma once
#include <cstdint>
#include "decode_execute_module/common.hpp"
#include "../instruction_opcodes_gen.hpp"

class Hart;

// NOTE: autogenerated - do not edit
// Generator: dsl/rv32i_executer_gen.rb

namespace riscv_sim {
namespace executer {

void execute(const DecodedInstruction instr, Hart& hart);

void execute_add(const DecodedInstruction instr, Hart& hart);
        void execute_sub(const DecodedInstruction instr, Hart& hart);
        void execute_sll(const DecodedInstruction instr, Hart& hart);
        void execute_slt(const DecodedInstruction instr, Hart& hart);
        void execute_sltu(const DecodedInstruction instr, Hart& hart);
        void execute_xor(const DecodedInstruction instr, Hart& hart);
        void execute_srl(const DecodedInstruction instr, Hart& hart);
        void execute_sra(const DecodedInstruction instr, Hart& hart);
        void execute_or(const DecodedInstruction instr, Hart& hart);
        void execute_and(const DecodedInstruction instr, Hart& hart);
        void execute_addi(const DecodedInstruction instr, Hart& hart);
        void execute_slti(const DecodedInstruction instr, Hart& hart);
        void execute_sltiu(const DecodedInstruction instr, Hart& hart);
        void execute_xori(const DecodedInstruction instr, Hart& hart);
        void execute_ori(const DecodedInstruction instr, Hart& hart);
        void execute_andi(const DecodedInstruction instr, Hart& hart);
        void execute_slli(const DecodedInstruction instr, Hart& hart);
        void execute_srli(const DecodedInstruction instr, Hart& hart);
        void execute_srai(const DecodedInstruction instr, Hart& hart);
        void execute_lb(const DecodedInstruction instr, Hart& hart);
        void execute_lh(const DecodedInstruction instr, Hart& hart);
        void execute_lw(const DecodedInstruction instr, Hart& hart);
        void execute_lbu(const DecodedInstruction instr, Hart& hart);
        void execute_lhu(const DecodedInstruction instr, Hart& hart);
        void execute_jalr(const DecodedInstruction instr, Hart& hart);
        void execute_sb(const DecodedInstruction instr, Hart& hart);
        void execute_sh(const DecodedInstruction instr, Hart& hart);
        void execute_sw(const DecodedInstruction instr, Hart& hart);
        void execute_beq(const DecodedInstruction instr, Hart& hart);
        void execute_bne(const DecodedInstruction instr, Hart& hart);
        void execute_blt(const DecodedInstruction instr, Hart& hart);
        void execute_bge(const DecodedInstruction instr, Hart& hart);
        void execute_bltu(const DecodedInstruction instr, Hart& hart);
        void execute_bgeu(const DecodedInstruction instr, Hart& hart);
        void execute_lui(const DecodedInstruction instr, Hart& hart);
        void execute_auipc(const DecodedInstruction instr, Hart& hart);
        void execute_jal(const DecodedInstruction instr, Hart& hart);
        void execute_ecall(const DecodedInstruction instr, Hart& hart);

} // namespace executer
} // namespace riscv_sim
