#pragma once
#include <cstdint>
#include "decode_execute_module/common.hpp"

// NOTE: autogenerated - do not edit
// Generator: dsl/rv32i_decoder_gen.rb

namespace riscv_sim {
namespace decoder {

DecodedInstruction decode(uint32_t instruction);

} // namespace decoder
} // namespace riscv_sim
