#include "rv32i_decoder_gen.hpp"
#include "decode_execute_module/common.hpp"
#include "../instruction_opcodes_gen.hpp"

// NOTE: autogenerated - do not edit
// Generator: dsl/rv32i_decoder_gen.rb

namespace riscv_sim {
namespace decoder {

uint8_t get_rd(uint32_t instruction) {
    return (instruction >> 7) & 0x1F;
}

uint8_t get_rs1(uint32_t instruction) {
    return (instruction >> 15) & 0x1F;
}

uint8_t get_rs2(uint32_t instruction) {
    return (instruction >> 20) & 0x1F;
}

uint8_t get_funct3(uint32_t instruction) {
    return (instruction >> 12) & 0x7;
}

uint8_t get_funct7(uint32_t instruction) {
    return (instruction >> 25) & 0x7F;
}

int32_t get_imm_i(uint32_t instruction) {
    return static_cast<int32_t>(instruction) >> 20;
}

int32_t get_imm_s(uint32_t instruction) {
    int32_t imm = ((instruction >> 25) & 0x7F) << 5;
    imm |= ((instruction >> 7) & 0x1F);
    return static_cast<int32_t>(imm << 20) >> 20;
}

int32_t get_imm_b(uint32_t instruction) {
    int32_t imm = ((instruction >> 31) & 0x1) << 12;
    imm |= ((instruction >> 25) & 0x3F) << 5;
    imm |= ((instruction >> 8) & 0xF) << 1;
    imm |= ((instruction >> 7) & 0x1) << 11;
    return static_cast<int32_t>(imm << 19) >> 19;
}

int32_t get_imm_u(uint32_t instruction) {
    return instruction & 0xFFFFF000;
}

int32_t get_imm_j(uint32_t instruction) {
    int32_t imm = ((instruction >> 31) & 0x1) << 20;
    imm |= ((instruction >> 21) & 0x3FF) << 1;
    imm |= ((instruction >> 20) & 0x1) << 11;
    imm |= ((instruction >> 12) & 0xFF) << 12;
    return static_cast<int32_t>(imm << 11) >> 11;
}

DecodedInstruction decode_lb(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::LB;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.imm = get_imm_i(instruction);

    return result;
}

DecodedInstruction decode_lh(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::LH;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.imm = get_imm_i(instruction);

    return result;
}

DecodedInstruction decode_lw(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::LW;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.imm = get_imm_i(instruction);

    return result;
}

DecodedInstruction decode_ld(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::LD;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.imm = get_imm_i(instruction);

    return result;
}

DecodedInstruction decode_lbu(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::LBU;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.imm = get_imm_i(instruction);

    return result;
}

DecodedInstruction decode_lhu(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::LHU;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.imm = get_imm_i(instruction);

    return result;
}

DecodedInstruction decode_lwu(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::LWU;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.imm = get_imm_i(instruction);

    return result;
}

DecodedInstruction decode_sb(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SB;
    result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = get_imm_s(instruction);

    return result;
}

DecodedInstruction decode_sh(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SH;
    result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = get_imm_s(instruction);

    return result;
}

DecodedInstruction decode_sw(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SW;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = get_imm_s(instruction);

    return result;
}

DecodedInstruction decode_sd(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SD;
    result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = get_imm_s(instruction);

    return result;
}

DecodedInstruction decode_addiw(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::ADDIW;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.imm = get_imm_i(instruction);

    return result;
}

DecodedInstruction decode_slliw(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SLLIW;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.imm = get_imm_i(instruction);

    return result;
}

DecodedInstruction decode_srliw(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SRLIW;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.imm = get_imm_i(instruction);

    return result;
}

DecodedInstruction decode_sraiw(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SRAIW;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.imm = get_imm_i(instruction);

    return result;
}

DecodedInstruction decode_addw(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::ADDW;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = 0;

    return result;
}

DecodedInstruction decode_subw(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SUBW;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = 0;

    return result;
}

DecodedInstruction decode_sllw(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SLLW;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = 0;

    return result;
}

DecodedInstruction decode_srlw(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SRLW;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = 0;

    return result;
}

DecodedInstruction decode_sraw(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SRAW;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = 0;

    return result;
}

DecodedInstruction decode_add(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::ADD;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = 0;

    return result;
}

DecodedInstruction decode_sub(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SUB;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = 0;

    return result;
}

DecodedInstruction decode_sll(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SLL;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = 0;

    return result;
}

DecodedInstruction decode_slt(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SLT;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = 0;

    return result;
}

DecodedInstruction decode_sltu(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SLTU;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = 0;

    return result;
}

DecodedInstruction decode_xor(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::XOR;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = 0;

    return result;
}

DecodedInstruction decode_srl(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SRL;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = 0;

    return result;
}

DecodedInstruction decode_sra(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SRA;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = 0;

    return result;
}

DecodedInstruction decode_or(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::OR;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = 0;

    return result;
}

DecodedInstruction decode_and(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::AND;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = 0;

    return result;
}

DecodedInstruction decode_addi(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::ADDI;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.imm = get_imm_i(instruction);

    return result;
}

DecodedInstruction decode_slti(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SLTI;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.imm = get_imm_i(instruction);

    return result;
}

DecodedInstruction decode_sltiu(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SLTIU;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.imm = get_imm_i(instruction);

    return result;
}

DecodedInstruction decode_xori(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::XORI;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.imm = get_imm_i(instruction);

    return result;
}

DecodedInstruction decode_ori(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::ORI;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.imm = get_imm_i(instruction);

    return result;
}

DecodedInstruction decode_andi(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::ANDI;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.imm = get_imm_i(instruction);

    return result;
}

DecodedInstruction decode_slli(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SLLI;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.imm = get_imm_i(instruction);

    return result;
}

DecodedInstruction decode_srli(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SRLI;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.imm = get_imm_i(instruction);

    return result;
}

DecodedInstruction decode_srai(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::SRAI;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.imm = get_imm_i(instruction);

    return result;
}

DecodedInstruction decode_jalr(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::JALR;
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.imm = get_imm_i(instruction);

    return result;
}

DecodedInstruction decode_beq(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::BEQ;
    result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = get_imm_b(instruction);

    return result;
}

DecodedInstruction decode_bne(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::BNE;
    result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = get_imm_b(instruction);

    return result;
}

DecodedInstruction decode_blt(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::BLT;
    result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = get_imm_b(instruction);

    return result;
}

DecodedInstruction decode_bge(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::BGE;
    result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = get_imm_b(instruction);

    return result;
}

DecodedInstruction decode_bltu(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::BLTU;
    result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = get_imm_b(instruction);

    return result;
}

DecodedInstruction decode_bgeu(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::BGEU;
    result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.imm = get_imm_b(instruction);

    return result;
}

DecodedInstruction decode_lui(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::LUI;
    result.rd = get_rd(instruction);
                result.imm = get_imm_u(instruction);

    return result;
}

DecodedInstruction decode_auipc(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::AUIPC;
    result.rd = get_rd(instruction);
                result.imm = get_imm_u(instruction);

    return result;
}

DecodedInstruction decode_jal(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::JAL;
    result.rd = get_rd(instruction);
                result.imm = get_imm_j(instruction);

    return result;
}

DecodedInstruction decode_ecall(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::ECALL;
    result.rd = get_rd(instruction);
                result.imm = get_imm_j(instruction);

    return result;
}


DecodedInstruction decode(uint32_t instruction) {
    DecodedInstruction result;
    result.opcode = InstructionOpcode::UNKNOWN;

    uint8_t opcode = instruction & 0x7F;
    switch (opcode) {
      
		case 3:
			switch (get_funct3(instruction)) {
				case 0:
					result = decode_lb(instruction);
					break;
				case 1:
					result = decode_lh(instruction);
					break;
				case 2:
					result = decode_lw(instruction);
					break;
				case 3:
					result = decode_ld(instruction);
					break;
				case 4:
					result = decode_lbu(instruction);
					break;
				case 5:
					result = decode_lhu(instruction);
					break;
				case 6:
					result = decode_lwu(instruction);
					break;
			}
			break;
 
		case 35:
			switch (get_funct3(instruction)) {
				case 0:
					result = decode_sb(instruction);
					break;
				case 1:
					result = decode_sh(instruction);
					break;
				case 2:
					result = decode_sw(instruction);
					break;
				case 3:
					result = decode_sd(instruction);
					break;
			}
			break;
 
		case 27:
			switch (get_funct3(instruction)) {
				case 0:
					result = decode_addiw(instruction);
					break;
				case 1:
					result = decode_slliw(instruction);
					break;
				case 5:
					switch (get_funct7(instruction)) {
						case 0: result = decode_srliw(instruction); break;
						case 32: result = decode_sraiw(instruction); break;
					}
					break;
			}
			break;
 
		case 59:
			switch (get_funct3(instruction)) {
				case 0:
					switch (get_funct7(instruction)) {
						case 0: result = decode_addw(instruction); break;
						case 32: result = decode_subw(instruction); break;
					}
					break;
				case 1:
					result = decode_sllw(instruction);
					break;
				case 5:
					switch (get_funct7(instruction)) {
						case 0: result = decode_srlw(instruction); break;
						case 32: result = decode_sraw(instruction); break;
					}
					break;
			}
			break;
 
		case 51:
			switch (get_funct3(instruction)) {
				case 0:
					switch (get_funct7(instruction)) {
						case 0: result = decode_add(instruction); break;
						case 32: result = decode_sub(instruction); break;
					}
					break;
				case 1:
					result = decode_sll(instruction);
					break;
				case 2:
					result = decode_slt(instruction);
					break;
				case 3:
					result = decode_sltu(instruction);
					break;
				case 4:
					result = decode_xor(instruction);
					break;
				case 5:
					switch (get_funct7(instruction)) {
						case 0: result = decode_srl(instruction); break;
						case 32: result = decode_sra(instruction); break;
					}
					break;
				case 6:
					result = decode_or(instruction);
					break;
				case 7:
					result = decode_and(instruction);
					break;
			}
			break;
 
		case 19:
			switch (get_funct3(instruction)) {
				case 0:
					result = decode_addi(instruction);
					break;
				case 2:
					result = decode_slti(instruction);
					break;
				case 3:
					result = decode_sltiu(instruction);
					break;
				case 4:
					result = decode_xori(instruction);
					break;
				case 6:
					result = decode_ori(instruction);
					break;
				case 7:
					result = decode_andi(instruction);
					break;
				case 1:
					result = decode_slli(instruction);
					break;
				case 5:
					switch (get_funct7(instruction)) {
						case 0: result = decode_srli(instruction); break;
						case 32: result = decode_srai(instruction); break;
					}
					break;
			}
			break;
 
		case 103:
			result = decode_jalr(instruction);
			break;
 
		case 99:
			switch (get_funct3(instruction)) {
				case 0:
					result = decode_beq(instruction);
					break;
				case 1:
					result = decode_bne(instruction);
					break;
				case 4:
					result = decode_blt(instruction);
					break;
				case 5:
					result = decode_bge(instruction);
					break;
				case 6:
					result = decode_bltu(instruction);
					break;
				case 7:
					result = decode_bgeu(instruction);
					break;
			}
			break;
 
		case 55:
			result = decode_lui(instruction);
			break;
 
		case 23:
			result = decode_auipc(instruction);
			break;
 
		case 111:
			result = decode_jal(instruction);
			break;
 
		case 115:
			result = decode_ecall(instruction);
			break;
        default:
            result.opcode = InstructionOpcode::UNKNOWN;
    }

    return result;
}

} // namespace decoder
} // namespace riscv_sim
