#pragma once
#include <cstdint>
#include "../../include/common.hpp"

// NOTE: autogenerated - do not edit
// Generator: rv32i_decoder_gen.rb

namespace riscv_sim {
namespace decoder {

DecodedInstruction decode(uint32_t instruction);

} // namespace decoder
} // namespace riscv_sim
