#include "rv32i_decoder_gen.hpp"
#include <iostream>
#include <sstream>
#include "../../include/common.hpp"
#include "../instruction_opcodes_gen.hpp"

// NOTE: autogenerated, do not edit manually
// Generator: rv32i_decoder_gen.rb
uint8_t RV32IDecoder::get_rd(uint32_t instruction) {
    return (instruction >> 7) & 0x1F;
}

uint8_t RV32IDecoder::get_rs1(uint32_t instruction) {
    return (instruction >> 15) & 0x1F;
}

uint8_t RV32IDecoder::get_rs2(uint32_t instruction) {
    return (instruction >> 20) & 0x1F;
}

uint8_t RV32IDecoder::get_funct3(uint32_t instruction) {
    return (instruction >> 12) & 0x7;
}

uint8_t RV32IDecoder::get_funct7(uint32_t instruction) {
    return (instruction >> 25) & 0x7F;
}

int32_t RV32IDecoder::get_imm_i(uint32_t instruction) {
    return static_cast<int32_t>(instruction) >> 20;
}

int32_t RV32IDecoder::get_imm_s(uint32_t instruction) {
    int32_t imm = ((instruction >> 25) & 0x7F) << 5;
    imm |= ((instruction >> 7) & 0x1F);
    return static_cast<int32_t>(imm << 20) >> 20;
}

int32_t RV32IDecoder::get_imm_b(uint32_t instruction) {
    int32_t imm = ((instruction >> 31) & 0x1) << 12;
    imm |= ((instruction >> 25) & 0x3F) << 5;
    imm |= ((instruction >> 8) & 0xF) << 1;
    imm |= ((instruction >> 7) & 0x1) << 11;
    return static_cast<int32_t>(imm << 19) >> 19;
}

int32_t RV32IDecoder::get_imm_u(uint32_t instruction) {
    return instruction & 0xFFFFF000;
}

int32_t RV32IDecoder::get_imm_j(uint32_t instruction) {
    int32_t imm = ((instruction >> 31) & 0x1) << 20;
    imm |= ((instruction >> 21) & 0x3FF) << 1;
    imm |= ((instruction >> 20) & 0x1) << 11;
    imm |= ((instruction >> 12) & 0xFF) << 12;
    return static_cast<int32_t>(imm << 11) >> 11;
}

// Instruction decoding methods
void RV32IDecoder::decode_add(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::ADD;
    result.name = "add";
    result.format = "R";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.funct3 = get_funct3(instruction);
                result.funct7 = get_funct7(instruction);
                result.imm = 0;
}

void RV32IDecoder::decode_sub(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::SUB;
    result.name = "sub";
    result.format = "R";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.funct3 = get_funct3(instruction);
                result.funct7 = get_funct7(instruction);
                result.imm = 0;
}

void RV32IDecoder::decode_sll(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::SLL;
    result.name = "sll";
    result.format = "R";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.funct3 = get_funct3(instruction);
                result.funct7 = get_funct7(instruction);
                result.imm = 0;
}

void RV32IDecoder::decode_slt(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::SLT;
    result.name = "slt";
    result.format = "R";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.funct3 = get_funct3(instruction);
                result.funct7 = get_funct7(instruction);
                result.imm = 0;
}

void RV32IDecoder::decode_sltu(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::SLTU;
    result.name = "sltu";
    result.format = "R";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.funct3 = get_funct3(instruction);
                result.funct7 = get_funct7(instruction);
                result.imm = 0;
}

void RV32IDecoder::decode_xor(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::XOR;
    result.name = "xor";
    result.format = "R";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.funct3 = get_funct3(instruction);
                result.funct7 = get_funct7(instruction);
                result.imm = 0;
}

void RV32IDecoder::decode_srl(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::SRL;
    result.name = "srl";
    result.format = "R";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.funct3 = get_funct3(instruction);
                result.funct7 = get_funct7(instruction);
                result.imm = 0;
}

void RV32IDecoder::decode_sra(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::SRA;
    result.name = "sra";
    result.format = "R";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.funct3 = get_funct3(instruction);
                result.funct7 = get_funct7(instruction);
                result.imm = 0;
}

void RV32IDecoder::decode_or(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::OR;
    result.name = "or";
    result.format = "R";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.funct3 = get_funct3(instruction);
                result.funct7 = get_funct7(instruction);
                result.imm = 0;
}

void RV32IDecoder::decode_and(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::AND;
    result.name = "and";
    result.format = "R";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.funct3 = get_funct3(instruction);
                result.funct7 = get_funct7(instruction);
                result.imm = 0;
}

void RV32IDecoder::decode_addi(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::ADDI;
    result.name = "addi";
    result.format = "I";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_i(instruction);
}

void RV32IDecoder::decode_slti(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::SLTI;
    result.name = "slti";
    result.format = "I";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_i(instruction);
}

void RV32IDecoder::decode_sltiu(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::SLTIU;
    result.name = "sltiu";
    result.format = "I";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_i(instruction);
}

void RV32IDecoder::decode_xori(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::XORI;
    result.name = "xori";
    result.format = "I";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_i(instruction);
}

void RV32IDecoder::decode_ori(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::ORI;
    result.name = "ori";
    result.format = "I";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_i(instruction);
}

void RV32IDecoder::decode_andi(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::ANDI;
    result.name = "andi";
    result.format = "I";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_i(instruction);
}

void RV32IDecoder::decode_slli(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::SLLI;
    result.name = "slli";
    result.format = "I";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.funct3 = get_funct3(instruction);
                result.funct7 = get_funct7(instruction);
                result.imm = get_imm_i(instruction);
}

void RV32IDecoder::decode_srli(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::SRLI;
    result.name = "srli";
    result.format = "I";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.funct3 = get_funct3(instruction);
                result.funct7 = get_funct7(instruction);
                result.imm = get_imm_i(instruction);
}

void RV32IDecoder::decode_srai(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::SRAI;
    result.name = "srai";
    result.format = "I";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.funct3 = get_funct3(instruction);
                result.funct7 = get_funct7(instruction);
                result.imm = get_imm_i(instruction);
}

void RV32IDecoder::decode_lb(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::LB;
    result.name = "lb";
    result.format = "I";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_i(instruction);
}

void RV32IDecoder::decode_lh(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::LH;
    result.name = "lh";
    result.format = "I";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_i(instruction);
}

void RV32IDecoder::decode_lw(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::LW;
    result.name = "lw";
    result.format = "I";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_i(instruction);
}

void RV32IDecoder::decode_lbu(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::LBU;
    result.name = "lbu";
    result.format = "I";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_i(instruction);
}

void RV32IDecoder::decode_lhu(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::LHU;
    result.name = "lhu";
    result.format = "I";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_i(instruction);
}

void RV32IDecoder::decode_jalr(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::JALR;
    result.name = "jalr";
    result.format = "I";
    result.rd = get_rd(instruction);
                result.rs1 = get_rs1(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_i(instruction);
}

void RV32IDecoder::decode_sb(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::SB;
    result.name = "sb";
    result.format = "S";
    result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_s(instruction);
}

void RV32IDecoder::decode_sh(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::SH;
    result.name = "sh";
    result.format = "S";
    result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_s(instruction);
}

void RV32IDecoder::decode_sw(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::SW;
    result.name = "sw";
    result.format = "S";
    result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_s(instruction);
}

void RV32IDecoder::decode_beq(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::BEQ;
    result.name = "beq";
    result.format = "B";
    result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_b(instruction);
}

void RV32IDecoder::decode_bne(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::BNE;
    result.name = "bne";
    result.format = "B";
    result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_b(instruction);
}

void RV32IDecoder::decode_blt(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::BLT;
    result.name = "blt";
    result.format = "B";
    result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_b(instruction);
}

void RV32IDecoder::decode_bge(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::BGE;
    result.name = "bge";
    result.format = "B";
    result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_b(instruction);
}

void RV32IDecoder::decode_bltu(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::BLTU;
    result.name = "bltu";
    result.format = "B";
    result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_b(instruction);
}

void RV32IDecoder::decode_bgeu(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::BGEU;
    result.name = "bgeu";
    result.format = "B";
    result.rs1 = get_rs1(instruction);
                result.rs2 = get_rs2(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_b(instruction);
}

void RV32IDecoder::decode_lui(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::LUI;
    result.name = "lui";
    result.format = "U";
    result.rd = get_rd(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_u(instruction);
}

void RV32IDecoder::decode_auipc(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::AUIPC;
    result.name = "auipc";
    result.format = "U";
    result.rd = get_rd(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_u(instruction);
}

void RV32IDecoder::decode_jal(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::JAL;
    result.name = "jal";
    result.format = "J";
    result.rd = get_rd(instruction);
                result.funct3 = get_funct3(instruction);
                result.imm = get_imm_j(instruction);
}

void RV32IDecoder::decode_ecall(uint32_t instruction, DecodedInstruction& result) {
    result.opcode = InstructionOpcode::ECALL;
    result.name = "ecall";
    result.format = "I";
    result.funct3 = get_funct3(instruction);
                result.imm = get_imm_i(instruction);
}


// Main decoding function
DecodedInstruction RV32IDecoder::decode(uint32_t instruction) {
    DecodedInstruction result;
    result.raw_instruction = instruction;
    uint8_t opcode = instruction & 0x7F;
    switch (opcode) {
        case 51:
 switch (get_funct3(instruction)) {
 case 0:
 switch (get_funct7(instruction)) {
 case 0: decode_add(instruction, result); break;
 case 32: decode_sub(instruction, result); break;
 }
 break;
 case 1:
 decode_sll(instruction, result); break;
 break;
 case 2:
 decode_slt(instruction, result); break;
 break;
 case 3:
 decode_sltu(instruction, result); break;
 break;
 case 4:
 decode_xor(instruction, result); break;
 break;
 case 5:
 switch (get_funct7(instruction)) {
 case 0: decode_srl(instruction, result); break;
 case 32: decode_sra(instruction, result); break;
 }
 break;
 case 6:
 decode_or(instruction, result); break;
 break;
 case 7:
 decode_and(instruction, result); break;
 break;
 }
 break;
 case 19:
 switch (get_funct3(instruction)) {
 case 0:
 decode_addi(instruction, result); break;
 break;
 case 2:
 decode_slti(instruction, result); break;
 break;
 case 3:
 decode_sltiu(instruction, result); break;
 break;
 case 4:
 decode_xori(instruction, result); break;
 break;
 case 6:
 decode_ori(instruction, result); break;
 break;
 case 7:
 decode_andi(instruction, result); break;
 break;
 case 1:
 decode_slli(instruction, result); break;
 break;
 case 5:
 switch (get_funct7(instruction)) {
 case 0: decode_srli(instruction, result); break;
 case 32: decode_srai(instruction, result); break;
 }
 break;
 }
 break;
 case 3:
 switch (get_funct3(instruction)) {
 case 0:
 decode_lb(instruction, result); break;
 break;
 case 1:
 decode_lh(instruction, result); break;
 break;
 case 2:
 decode_lw(instruction, result); break;
 break;
 case 4:
 decode_lbu(instruction, result); break;
 break;
 case 5:
 decode_lhu(instruction, result); break;
 break;
 }
 break;
 case 103:
 decode_jalr(instruction, result); break;
 break;
 case 35:
 switch (get_funct3(instruction)) {
 case 0:
 decode_sb(instruction, result); break;
 break;
 case 1:
 decode_sh(instruction, result); break;
 break;
 case 2:
 decode_sw(instruction, result); break;
 break;
 }
 break;
 case 99:
 switch (get_funct3(instruction)) {
 case 0:
 decode_beq(instruction, result); break;
 break;
 case 1:
 decode_bne(instruction, result); break;
 break;
 case 4:
 decode_blt(instruction, result); break;
 break;
 case 5:
 decode_bge(instruction, result); break;
 break;
 case 6:
 decode_bltu(instruction, result); break;
 break;
 case 7:
 decode_bgeu(instruction, result); break;
 break;
 }
 break;
 case 55:
 decode_lui(instruction, result); break;
 break;
 case 23:
 decode_auipc(instruction, result); break;
 break;
 case 111:
 decode_jal(instruction, result); break;
 break;
 case 115:
 decode_ecall(instruction, result); break;
 break;
        default:
            result.opcode = InstructionOpcode::UNKNOWN;
            result.name = "UNKNOWN";
            result.format = "UNKNOWN";
    }
    
    return result;
}

// Disassembly function
std::string RV32IDecoder::disassemble(const DecodedInstruction& instr) {
    std::stringstream ss;
    ss << instr.name;
    
    if (instr.format == "R") {
        ss << " x" << static_cast<int>(instr.rd) 
           << ", x" << static_cast<int>(instr.rs1) 
           << ", x" << static_cast<int>(instr.rs2);
    } else if (instr.format == "I") {
        if (instr.name == "jalr") {
            ss << " x" << static_cast<int>(instr.rd) 
               << ", " << instr.imm 
               << "(x" << static_cast<int>(instr.rs1) << ")";
        } else if (instr.name.find("l") == 0) {  // loads: lb,lh,lw,lbu,lhu
            ss << " x" << static_cast<int>(instr.rd) 
               << ", " << instr.imm 
               << "(x" << static_cast<int>(instr.rs1) << ")";
        } else if (instr.name == "ecall" || instr.name == "ebreak") {
            ss << "";  // No operands
        } else {
            ss << " x" << static_cast<int>(instr.rd) 
               << ", x" << static_cast<int>(instr.rs1) 
               << ", " << instr.imm;
        }
    } else if (instr.format == "S") {
        ss << " x" << static_cast<int>(instr.rs2) 
           << ", " << instr.imm 
           << "(x" << static_cast<int>(instr.rs1) << ")";
    } else if (instr.format == "B") {
        ss << " x" << static_cast<int>(instr.rs1) 
           << ", x" << static_cast<int>(instr.rs2) 
           << ", " << instr.imm;
    } else if (instr.format == "U") {
        ss << " x" << static_cast<int>(instr.rd) 
           << ", " << (instr.imm >> 12);
    } else if (instr.format == "J") {
        ss << " x" << static_cast<int>(instr.rd) 
           << ", " << instr.imm;
    }
    
    return ss.str();
}
